config/routes.rb
Rails.application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config



  ActiveAdmin.routes(self)
  resources :clients do
    resources :companies
  end

  resources :companies, except: [:new, :create, :index] do
    resources :workers
  end

root to: "clients#index"

  resources :workers, except: [:new, :create, :index] do
    resources :family_burdens
  end

  resources :workers do
    resources :remunerations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :companies
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :client_rut)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Rut %>
    <%= form.text_field :client_rut, id: :client_client_rut %>
  </div>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_client' %>
 <% end %>

<h1>Editar Cliente</h1>

<%= render 'form', client: @client %>

<%= link_to 'Volver', clients_path %>

app/views/clients/index.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_clients' %>
 <% end %>

<h1>Clientes</h1>

<br>

<table id="myTable" class="table">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.client_rut %></td>
        <td><%= client.name %></td>
        <td><%= link_to 'Mostrar', client %>
        <%= link_to 'Editar', edit_client_path(client) %>
        <%= link_to 'Borrar', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/clients/new.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_client' %>
 <% end %>

<h1>Nuevo Cliente</h1>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_show_client' %>
 <% end %>

<p>
  <h1><%= @client.name %></h1>
</p>

<p>
  <strong>Rut:</strong>
  <%= @client.client_rut %>
</p>

<br>
<br>

<table id="myTable" class="table">
  <thead>
    <tr>
      <th>Rut Empresa</th>
      <th>Nombre Empresa</th>
      <th>Opciones</th>
    </tr>
  </thead>

<h2>Empresas</h2>

  <tbody>
    <% @client.companies.each do |company| %>
      <tr>
        <td><%= company.taxpayer_id_company %></td>
        <td><%= company.business_name %></td>
        <td><%= link_to 'Mostrar', client_company_path(company.client, company) %>
        <%= link_to 'Editar', edit_client_company_path(company.client, company) %>
        <%= link_to 'Borrar', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>