config/routes.rb
Rails.application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config



  ActiveAdmin.routes(self)
  resources :clients do
    resources :companies
  end

  resources :companies, except: [:new, :create, :index] do
    resources :workers
  end

root to: "clients#index"

  resources :workers, except: [:new, :create, :index] do
    resources :family_burdens
  end

  resources :workers do
    resources :remunerations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :client
  has_many :workers
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.where(client_id: params[:client_id])
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
    @company.client = Client.find(params[:client_id])
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    @company.client = Client.find(params[:client_id])
    respond_to do |format|
      if @company.save
        format.html { redirect_to client_path(@company.client), notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to client_path(@company.client), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to client_path(@company.client), notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:taxpayer_id_company, :business_name)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, url: client_companies_path(params[:client_id])) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Rut_empresa %>
    <%= form.text_field :taxpayer_id_company, id: :company_taxpayer_id_company %>
  </div>

  <div class="field">
    <%= form.label :Nombre_empresa %>
    <%= form.text_field :business_name, id: :company_business_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_update.html.erb
<%= form_with(model: company, url: client_company_path(company.client, company)) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :taxpayer_id_company %>
    <%= form.text_field :taxpayer_id_company, id: :company_taxpayer_id_company %>
  </div>

  <div class="field">
    <%= form.label :business_name %>
    <%= form.text_field :business_name, id: :company_business_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_company' %>
 <% end %>

<h1>Editar Compañía</h1>

<%= render 'update', company: @company %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Taxpayer id company</th>
      <th>Business name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.taxpayer_id_company %></td>
        <td><%= company.business_name %></td>
        <td><%= link_to 'Show', client_company_path(company.client, company) %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_client_company_path %>

app/views/companies/new.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_company' %>
 <% end %>

<h1>Nueva Compañía</h1>

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_show_company' %>
 <% end %>

<p id="notice"><%= notice %></p>

<p>
  <h1><%= @company.business_name %></h1>
</p>

<p>
  <strong>Rut:</strong>
  <%= @company.taxpayer_id_company %>
</p>

<br>

<h2>Trabajadores</h2>
<br>

<table id="myTable" class="table">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @company.workers.each do |worker| %>
      <tr>
        <td><%= worker.rut %></td>
        <td><%= worker.first_name %> <%= worker.last_name1 %> <%= worker.last_name2 %></td>
        <td><%= link_to 'Mostrar', company_worker_path(worker.company, worker) %>
        <%= link_to 'Editar', edit_company_worker_path(worker.company, worker) %>
        <%= link_to 'Borrar', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>