config/routes.rb
Rails.application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config



  ActiveAdmin.routes(self)
  resources :clients do
    resources :companies
  end

  resources :companies, except: [:new, :create, :index] do
    resources :workers
  end

root to: "clients#index"

  resources :workers, except: [:new, :create, :index] do
    resources :family_burdens
  end

  resources :workers do
    resources :remunerations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/sidebars/_sidebar.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
<%= link_to 'Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_clients.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Nuevo Cliente', new_client_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_index_remuneration.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Nueva Liquidación', new_worker_remuneration_path , class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver a Trabajador', (worker_path(@worker)), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_new_client.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Volver a listado clientes', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_new_company.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Volver', client_path(@company.client), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_new_familyburden.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Volver', worker_path(@family_burden.worker), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_new_remuneration.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Volver', worker_remunerations_path, class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_new_worker.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Volver a trabajador', company_path(@worker.company), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_show_client.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to "Editar a #{@client.name}", edit_client_path(@client), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Crear Empresa', new_client_company_path(@client), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_show_company.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to "Editar #{@company.business_name}", edit_company_path(@company), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Crear Trabajador', new_company_worker_path(@company), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to "Volver a #{@company.client.name}", client_path(@company.client), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_show_familyburden.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to 'Edita Carga Familiar', edit_worker_family_burden_path(@family_burden), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver',company_worker_path(@family_burden.worker.company.id, @family_burden.worker.id), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_show_remuneration.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to "Editar Liquidación", edit_worker_remuneration_path(@remuneration.worker, @remuneration), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to "Volver a Liquidaciones", worker_remunerations_path(@remuneration.worker), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver a Trabajador', worker_path(@remuneration.worker), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>

app/views/layouts/sidebars/_sidebar_show_worker.html.erb
<!-- Sidebar -->
<nav class="w3-sidebar w3-bar-block w3-collapse w3-large w3-theme-l5 w3-animate-left" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-right w3-xlarge w3-padding-large w3-hover-black w3-hide-large" title="Close Menu">
    <i class="fa fa-remove"></i>
  </a>
  <h4 class="w3-bar-item"><b>Menu</b></h4>
  <%= link_to "Editar a #{@worker.first_name}", edit_company_worker_path(@worker.company, @worker), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Agregar Carga Familiar', new_worker_family_burden_path(@worker.id), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Remuneraciones Trabajador', worker_remunerations_path(@worker.id), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to "Volver a #{@worker.company.business_name}", company_path(@worker.company), class: "w3-bar-item w3-button w3-hover-black" %>
  <%= link_to 'Volver Inicio', clients_path, class: "w3-bar-item w3-button w3-hover-black" %>
</nav>