config/routes.rb
Rails.application.routes.draw do


  devise_for :users, ActiveAdmin::Devise.config



  ActiveAdmin.routes(self)
  resources :clients do
    resources :companies
  end

  resources :companies, except: [:new, :create, :index] do
    resources :workers
  end

root to: "clients#index"

  resources :workers, except: [:new, :create, :index] do
    resources :family_burdens
  end

  resources :workers do
    resources :remunerations
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/worker.rb
class Worker < ApplicationRecord
  belongs_to :company
  has_many :family_burdens, :dependent => :delete_all

  has_one :health_plan, :dependent => :destroy
  accepts_nested_attributes_for :health_plan

  has_one :base_salary, :dependent => :destroy
  accepts_nested_attributes_for :base_salary

  has_one :pension_fund, :dependent => :destroy
  accepts_nested_attributes_for :pension_fund

  has_many :remunerations, :dependent => :delete_all

  def full_name
    first_name + " " + middle_name + " " + last_name1 + " " + last_name2
  end

  def company_details
    {name: company.business_name, rut: company.taxpayer_id_company}
  end

  def health_plan_details
    {name: health_plan.name, deduction: health_plan.deduction}
  end

  def base_salary_amount
    base_salary.amount
  end

  mount_uploader :file, FileUploader

end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all
  end

  # GET /workers/1
  # GET /workers/1.json
  def show
  end

  # GET /workers/new
  def new
    @worker = Worker.new
    @worker.company = Company.find(params[:company_id])
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)
    @worker.health_plan = HealthPlan.new(health_plan_params)
    @worker.base_salary = BaseSalary.new(base_salary_params)
    @worker.pension_fund = PensionFund.new(pension_fund_params)
    @worker.company = Company.find(params[:company_id])
    respond_to do |format|
      if @worker.save
        format.html { redirect_to company_path(@worker.company), notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params) && @worker.health_plan.update(health_plan_params) && @worker.base_salary.update(base_salary_params) && @worker.pension_fund.update(pension_fund_params)
        format.html { redirect_to company_path(@worker.company), notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to company_path(@worker.company), notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # def set_company
    #   @company = Company.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:rut, :first_name, :middle_name, :last_name1, :last_name2, :birthdate,:gender, :email, :phone, :address_region, :address_city, :address_street, :address_number, :address_apartment, :file)
    end

    def health_plan_params
      params.require(:worker).require(:health_plan_attributes).permit(:name, :deduction)
    end

    def base_salary_params
      params.require(:worker).require(:base_salary_attributes).permit(:amount)
    end

    def pension_fund_params
      params.require(:worker).require(:pension_fund_attributes).permit(:name, :deduction)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_with(model: worker, url: company_workers_path(params[:company_id])) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h3>Datos Trabajador</h3>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut, id: :worker_rut %>
  </div>

  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :first_name, id: :worker_first_name %>
  </div>

  <div class="field">
    <%= form.label :'Segundo nombre' %>
    <%= form.text_field :middle_name, id: :worker_middle_name %>
  </div>

  <div class="field">
    <%= form.label :'Primer apellido' %>
    <%= form.text_field :last_name1, id: :worker_last_name1 %>
  </div>

  <div class="field">
    <%= form.label :'Segundo apellido' %>
    <%= form.text_field :last_name2, id: :worker_last_name2 %>
  </div>

  <div class="field">
    <%= form.label :'Fecha de nacimiento' %>
    <%= form.date_field :birthdate, id: :worker_birthdate %>
  </div>

  <div class="field">
    <%= form.label :'Sexo' %>
    <%= form.select :gender, ['Masculino', 'Femenino'], id: :worker_gender %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email, id: :worker_email %>
  </div>

  <div class="field">
    <%= form.label :Teléfono %>
    <%= form.text_field :phone, id: :worker_phone %>
  </div>

  <div class="field">
    <%= form.label :Región %>
    <%= form.select :address_region, ['Metropolitana de Santiago', 'XV de Arica y Parinacota', 'I de Tarapacá',
      'II de Antofagasta', 'III de Atacama', 'IV de Coquimbo', 'V de Valparaíso',
      "VI del Libertador General Bernardo O'Higgins", 'VII del Maule', 'VII del Bío Bío', 'IX de la Araucanía',
      'XIV de los Ríos', 'X de los Lagos', '	XI Aisén del General Carlos Ibáñez del Campo',
      'XII de Magallanes y Antártica Chilena'], id: :worker_address_region %>
  </div>

  <div class="field">
    <%= form.label :Comuna %>
    <%= form.text_field :address_city, id: :worker_address_city %>
  </div>

  <div class="field">
    <%= form.label :Calle %>
    <%= form.text_field :address_street, id: :worker_address_street %>
  </div>

  <div class="field">
    <%= form.label :Número %>
    <%= form.text_field :address_number, id: :worker_address_number %>
  </div>

  <div class="field">
    <%= form.label :'Depto / Casa' %>
    <%= form.text_field :address_apartment, id: :worker_address_apartment %>
  </div>

  <br>
  <h3>Sueldo Base Trabajador</h3>
  <%= form.fields_for :base_salary, BaseSalary.new(worker_id: worker) do |of| %>

    <div class="field">
      <%= of.label :Sueldo_base %>
      <%= of.number_field :amount %>
    </div>
    <% end %>

  <br>
  <h3>Plan de Salud Trabajador</h3>
  <%= form.fields_for :health_plan, HealthPlan.new(worker_id: worker) do |of| %>

    <div class="field">
      <%= of.label :Nombre_institución %>
      <%= of.text_field :name %>
    </div>

    <div class="field">
      <%= of.label :'% de descuento' %>
      <%= of.number_field :deduction, class: :text_field, step: :any %>
    </div>

  <% end %>

  <br>
  <h3>AFP Trabajador</h3>
  <%= form.fields_for :pension_fund, PensionFund.new(worker_id: worker) do |of| %>

    <div class="field">
      <%= of.label :Nombre_AFP %>
      <%= of.text_field :name %>
    </div>

    <div class="field">
      <%= of.label :'% de descuento' %>
      <%= of.number_field :deduction, class: :text_field, step: :any %>
  </div>

  <br>

  <h3>Documentos Anexos</h3>

  <div class="field">
    <%= form.file_field :file, id: :file_field %>
  </div>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/_update.html.erb
<%= form_with(model: worker, url: company_worker_path(params[:company_id], worker)) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
        <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<br>
<table class="table">
  <tr>
    <th><h5>Datos Personales</h5></th>
    <th><h5>Información de contacto</h5></th>
  </tr>
  <tr>
    <td><strong>Rut:</strong> <%= form.text_field :rut, id: :worker_rut %></td>
    <td><strong>Email:</strong> <%= form.text_field :email, id: :worker_email %></td>
  </tr>
  <tr>
    <td><strong>Primer nombre:</strong> <%= form.text_field :first_name, id: :worker_first_name %></td>
    <td><strong>Phone:</strong> <%= form.text_field :phone, id: :worker_phone %></td>
  </tr>

  <tr>
    <td><strong>Segundo nombre:</strong> <%= form.text_field :middle_name, id: :worker_middle_name %></td>
    <td><strong>Región:</strong> <%= form.select :address_region, ['Metropolitana de Santiago', 'XV de Arica y Parinacota', 'I de Tarapacá', 'II de Antofagasta', 'III de Atacama', 'IV de Coquimbo', 'V de Valparaíso', "VI del Libertador General Bernardo O'Higgins", 'VII del Maule', 'VII del Bío Bío', 'IX de la Araucanía', 'XIV de los Ríos', 'X de los Lagos', '	XI Aisén del General Carlos Ibáñez del Campo', 'XII de Magallanes y Antártica Chilena'], id: :worker_address_region %></td>
  </tr>
  <tr>
    <td><strong>Primer apellido:</strong> <%= form.text_field :last_name1, id: :worker_last_name1 %></td>
    <td><strong>Ciudad:</strong> <%= form.text_field :address_apartment, id: :worker_address_apartment %></td>
  </tr>
  <tr>
    <td><strong>Segundo apellido:</strong> <%= form.text_field :last_name2, id: :worker_last_name2 %></td>
    <td><strong>Calle:</strong> <%= form.text_field :address_street, id: :worker_address_street %></td>
  </tr>
<tr>
  <td><strong>Fechas de nacimiento:</strong> <%= form.date_field :birthdate, id: :worker_birthdate %></td>
  <td><strong>Número dirección:</strong> <%= form.text_field :address_number, id: :worker_address_number %></td>
</tr>
<tr>
  <td>
    <strong>Género:</strong> <%= form.select :gender, ['Masculino', 'Femenino'], id: :worker_gender %></td>
    <td><strong>N° casa o depto:</strong> <%= form.text_field :address_apartment, id: :worker_address_apartment %></td>
</tr>
  </table>


   <br>
    <h3>Sueldo Base Trabajador</h3>
    <%= form.fields_for :base_salary, worker.base_salary do |of| %>

      <div class="field">
        <%= of.label :Sueldo_base %>
        <%= of.number_field :amount %>
      </div>
    <% end %>

    <br>
    <h3>Plan de Salud Trabajador</h3>

    <%= form.fields_for :health_plan, worker.health_plan do |of| %>

      <div class="field">
        <%= of.label :Nombre_institución %>
        <%= of.text_field :name %>
      </div>

      <div class="field">
        <%= of.label :Descuento %>
        <%= of.text_field :deduction, autocomplete: "address" %>
      </div>

    <% end %>

      <br>
      <h3>AFP Trabajador</h3>

      <%= form.fields_for :pension_fund, worker.pension_fund do |of| %>
        <div class="field">

          <%= of.label :Nombre_AFP %>
          <%= of.text_field :name %>
        </div>

        <div class="field">
          <%= of.label :Descuento %>
          <%= of.text_field :deduction, autocomplete: "address" %>
        </div>

      <% end %>

      <br>
      <h3>Documentos Anexos</h3>

      <div class="field">
        <%= form.file_field :file, id: :file_field %>
      </div>

      <br>
      <div class="actions">
        <%= form.submit %>
      </div>



  <br>
  <br>
<% end %>

app/views/workers/edit.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_worker' %>
 <% end %>

<h1>Editar Datos Trabajador</h1>

<%= render 'update', worker: @worker %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>

<table>
  <thead>
    <tr>
      <th>Rut</th>
      <th>First name</th>
      <th>Middle name</th>
      <th>Last name1</th>
      <th>Last name2</th>
      <th>Birthdate</th>
      <th>Gender</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address region</th>
      <th>Address city</th>
      <th>Address street</th>
      <th>Address number</th>
      <th>Address apartment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.rut %></td>
        <td><%= worker.first_name %></td>
        <td><%= worker.middle_name %></td>
        <td><%= worker.last_name1 %></td>
        <td><%= worker.last_name2 %></td>
        <td><%= worker.birthdate %></td>
        <td><%= worker.gender %></td>
        <td><%= worker.email %></td>
        <td><%= worker.phone %></td>
        <td><%= worker.address_region %></td>
        <td><%= worker.address_city %></td>
        <td><%= worker.address_street %></td>
        <td><%= worker.address_number %></td>
        <td><%= worker.address_apartment %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

app/views/workers/new.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_new_worker' %>
 <% end %>

<h1>Nuevo Trabajador</h1>

<%= render 'form', worker: @worker %>

app/views/workers/show.html.erb
<% content_for :sidebar do %>
      <%= render 'layouts/sidebars/sidebar_show_worker' %>
 <% end %>

<p id="notice"><%= notice %></p>

<h1>Datos Trabajador</h1>

<br>
<table class="table">
  <tr>
    <th><h5>Datos Personales</h5></th>
    <th><h5>Información de contacto</h5></th>
  </tr>
  <tr>
    <td><strong>Rut:</strong> <%= @worker.rut %></td>
    <td><strong>Email:</strong> <%= @worker.email %></td>
  </tr>
  <tr>
    <td><strong>Primer nombre:</strong> <%= @worker.first_name %></td>
    <td><strong>Phone:</strong> <%= @worker.phone %></td>
  </tr>

  <tr>
    <td><strong>Segundo nombre:</strong> <%= @worker.middle_name %></td>
    <td><strong>Región:</strong> <%= @worker.address_region %></td>
  </tr>
  <tr>
    <td><strong>Primer apellido:</strong> <%= @worker.last_name1 %></td>
    <td><strong>Ciudad:</strong> <%= @worker.address_city %></td>
  </tr>
  <tr>
    <td><strong>Segundo apellido:</strong> <%= @worker.last_name2 %></td>
    <td><strong>Calle:</strong> <%= @worker.address_street %></td>
  </tr>
<tr>
  <td><strong>Fechas de nacimiento:</strong> <%= @worker.birthdate %></td>
  <td><strong>Número dirección:</strong> <%= @worker.address_number %></td>
</tr>
<tr>
  <td>
    <strong>Género:</strong> <%= @worker.gender %></td>
    <td><strong>N° casa o depto:</strong> <%= @worker.address_apartment %></td>
</tr>
  </table>

<br>

<h3>Cargas Familiares</h3>

<table class="table">
  <thead>
    <tr>
      <th>Rut</th>
      <th>Name</th>
      <th>Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @worker.family_burdens.each do |family_burden| %>
      <tr>
        <td><%= family_burden.rut %></td>
        <td><%= family_burden.name %></td>
        <td><%= link_to 'Mostrar', worker_family_burden_path(family_burden.worker, family_burden) %>
        <%= link_to 'Editar', edit_worker_family_burden_path(family_burden.worker, family_burden) %>
        <%= link_to 'Borrar', worker_family_burden_path(family_burden.worker, family_burden), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>


</table>

<br>
<h3>Documentos Anexos</h3>
  <%= link_to 'Anexos', @worker.file.url %>